# Generated by Django 4.2.13 on 2024-06-02 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={"verbose_name": "ブログ記事", "verbose_name_plural": "ブログ記事"},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "カテゴリ名", "verbose_name_plural": "カテゴリ名"},
        ),
    ]
